### ISSUE TITLE
Repository findOneBy

### ISSUE THREAD

**Issue by abdellahrk** [manuxi/SuluNewsBundle#3]
Very nice Bundle. Thank you for this.
Since the path to the article is generated in a slug form, with what field can this slugged be used with when fetching a single article/news for the show controller? example: `findOneBy(['slug' => $sluggedUrl])` 
@manuxi

**Comment by manuxi** [comment]
Thank you for your kind words. 
I've created the entities with traits for several properties, to have a better reuse on other bundles. To fit your needs you have to look at the Entity/NewsTranslation class, there you'll see that the RoutePathTrait is used.
Since the news are translatable and the routePath is inside a tranlation, you should fetch the news also with the locale (don't know if the slug is sufficient for identifying).
Therefor the whole thing should look like findOneBy(['locale' => $locale, 'routePath' => $sluggedUrl]) [untested]

**Comment by manuxi** [comment]
Did this fix your issue?

**Comment by abdellahrk** [comment]
Hello @manuxi, I am yet to try it out. I earlier used a hack where I passed the item id as a query string and find the item by that id. I will try in a bit and report back before closing the issue. 
Thank you very much for the care.

**Comment by abdellahrk** [comment]
This error `Unrecognized field: Manuxi\SuluNewsBundle\Entity\News::$routePath` and this `Unrecognized field: Manuxi\SuluNewsBundle\Entity\News::$locale`
@manuxi

**Comment by manuxi** [comment]
Please take a look in the Repository class to see how its done

**Comment by abdellahrk** [comment]
What I want to achieve is to have the single news item page. Since I need a custom controller for this. @manuxi

**Comment by manuxi** [comment]
No. Usually I create the list of news with smart-content. The elements do point to the routhPath (e.g. /news/my-first-news), there you should see the news. Did you use the bundle already? Than you should see the preview already.

**Comment by abdellahrk** [comment]
Hi @manuxi, thanks for the extended convo. Yes, the issue is that I get `No route found for "GET http://hey.build/news/my-first-news-ever"` is I don't declare  a custom route pointing to a single item.
Maybe I am wrong somewhere.

**Comment by manuxi** [comment]
Well this here is intended to track issues. _Not for personal support._ I strongly suggest the Sulu Slack.
If there is a bug, I will do the best I can to fix it. Then please provide as many info as you can. Just saying "It does not work" does not help. You also did not tell what you have tried so far. My crystal sphere doesn't help here.
- Do you see the element in the preview? Then the Controller is working. You have not told that.
- Did you create a news element and try to see it on your site? 
- What error do you get, if not? 
- Did you look into the code? 
- Did you see the NewsController? 
- What info does the profiler give you? 
- What does php bin/websiteconsole debug:container show (filter: news)? Do you see the NewsRouteDefaultsProvider?
- Did you test this bundle on a fresh environment (since you faced weird problems already I would strongly suggest that)?

**Comment by abdellahrk** [comment]
Thank you for your time and efforts.
Warmest regards.
